### ISSUE TITLE
Heroku endpoint URL 404 

### ISSUE THREAD

**Issue by upjoes** [teddis/alexa_bypass_nlp#1]
I have set up the app as instructed on https://www.linkedin.com/pulse/how-bypass-alexas-nlp-jump-warp-10-ted-cohn. I have deployed the app to Heroku at https://ancient-plains-99458.herokuapp.com. When I try and test it in the Service Simulator it looks like it is making a POST to https://ancient-plains-99458.herokuapp.com which results in a 404 as this route is set up as a GET. I can see a users route and the index route only so I am a bit confused at how this is supposed to work. Could you shed any light on this issue? What is the correct endpoint full URL that should be used in the Service Simulator? Am I missing something really obvious on the routing here?

**Comment by teddis** [comment]
Hi @upjoes, I'm sorry you're having trouble. I've made a fresh clone of this project to see if I could replicate your issue, but it works fine for me. Can you make sure on your Alexa dashboard "Configuration" tab that the Endpoint is set to "HTTPS", "North America" and the URL is ` https://ancient-plains-99458.herokuapp.com/alexa/copycat`? I assume you have also run `npm install` to load your packages and you are launching bin/www within the project. Hope this helps.

**Comment by upjoes** [comment]
I am seeing the following in my Heroku logs now when testing via the Service Simulator. Do you have any idea why this could be? Do you think this is to do with the configuration in the app or on AWS? Thanks for your help so far!

error handler!  NO_INTENT_FOUND

**Comment by teddis** [comment]
Without more info, my guess is that you may not have set up the interaction model as described. Did you specify the schema, `CatchAll` custom slot type and utterance from the project? My experience has been that you should always receive the single `catchAllIntent` intent. It might be easier if you connect and chat with me on [LinkedIn](http://www.linkedin.com/in/tedcohn) to debug this offline, then return here with the solution.

**Comment by upjoes** [comment]
We have it working now and I believe it was because of misconfiguration in AWS as you expected. My apologies.

**Comment by teddis** [comment]
Great!
